on:
  pull_request:
    paths:
      - '**.go'
      - '**.yml'
      - 'go.mod'
jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          golangci_lint_flags: "--config=.golangci.yml"
          level: warning
          reporter: github-pr-review
          fail_on_error: true
